### ISSUE TITLE
Error during mshr import

### ISSUE THREAD

**Issue by stschroe** [conda-forge/mshr-feedstock#18]
Issue:
during mshr import an error occured

File "..", line 1 ...
    from mshr import *
File "/anaconda3/ ... /lib/python3.7/site-packages/mshr/__init__.py", line 24, in <module>
    from .cpp import Circle
ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable"

see also:
https://fenicsproject.discourse.group/t/anaconda-installation-of-fenics-and-mshr/2062
but the proposed fix (delete imports in __init__) did not work 

<br/>
Environment (<code>conda list</code>):

linux ubuntu 16.4

mshr  linux-64  v2019.1.0

installed (linux-64  v2019.1.0):
conda install -c conda-forge fenics 
conda install -c conda-forge mshr
<details>
  

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by minrk** [comment]
Can you share the output of `conda list`?

**Comment by ashwinvis** [comment]
I got the same issue.

<summary>Here is `conda list`
<details>

```sh
 20s
(fenicsproject) ❯ python -c 'import mshr'  
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/avmo/.conda/envs/fenicsproject/lib/python3.8/site-packages/mshr/__init__.py", line 24, in <module>
    from .cpp import Circle
ImportError: generic_type: type "CSGGeometry" referenced unknown base type "dolfin::Variable"

~
(fenicsproject) ❯ conda list                                                                 
# packages in environment at /home/avmo/.conda/envs/fenicsproject:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py38h1e0a361_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_7    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.16.1               h516909a_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38h5bae8af_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
cmake                     3.18.0               h5c55442_0    conda-forge
cryptography              3.0              py38h766eaa4_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
eigen                     3.3.7             hc9558a2_1001    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py38h1e0a361_1    conda-forge
fenics                    2019.1.0        py38h32f6830_10    conda-forge
fenics-dijitso            2019.1.0                  py_10    conda-forge
fenics-dolfin             2019.1.0        py38hd3deb98_10    conda-forge
fenics-ffc                2019.1.0                  py_10    conda-forge
fenics-fiat               2019.1.0                  py_10    conda-forge
fenics-libdolfin          2019.1.0            h8f7d7a8_10    conda-forge
fenics-ufl                2019.1.0                  py_10    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py38h04dde30_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
hdf5                      1.10.6          mpi_mpich_ha7d0aea_1    conda-forge
hypre                     2.18.2               hc98498a_1    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
ipython                   7.17.0           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.17.2           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
jupyterlab                2.2.4                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               hfafb76e_2    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_4    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libev                     4.33                 h516909a_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_14    conda-forge
libgfortran-ng            7.5.0               hdf63c60_14    conda-forge
libgomp                   9.3.0               h24d8f2e_14    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.18               h516909a_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_14    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libuv                     1.38.0               h516909a_0    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
matplotlib-base           3.3.0            py38h91b0d89_1    conda-forge
metis                     5.1.0             he1b5a44_1005    conda-forge
mistune                   0.8.4           py38h1e0a361_1001    conda-forge
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpi4py                    3.0.3            py38h4a80816_1    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mshr                      2019.1.0         py38hf9f41d3_3    conda-forge
mumps-include             5.2.1                         6    conda-forge
mumps-mpi                 5.2.1                h645f208_6    conda-forge
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
notebook                  6.1.1            py38h32f6830_0    conda-forge
nspr                      4.27                 he1b5a44_1    conda-forge
nss                       3.55                 he751ad9_0    conda-forge
numpy                     1.19.1           py38h8854b6b_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.10.1               h516909a_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmetis                  4.0.3             h9f7b9cf_1005    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
petsc                     3.12.4               h432f2ec_0    conda-forge
petsc4py                  3.12.0           py38h30bdb2a_4    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
pkg-config                0.29.2            h516909a_1006    conda-forge
pkgconfig                 1.4.0            py38h32f6830_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.6                      py_0    conda-forge
prompt_toolkit            3.0.6                         0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptscotch                  6.0.8                he9f2703_1    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pybind11                  2.5.0            py38hbf85e49_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38ha8c2ead_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.5           h4d41432_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pyzmq                     19.0.2           py38ha71036d_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
scalapack                 2.0.2             hfacbc1e_1008    conda-forge
scotch                    6.0.8                h0eec0ba_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.3.1           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
slepc                     3.12.2               h76dbdef_0    conda-forge
slepc4py                  3.12.0           py38hb2ee469_1    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
suitesparse               5.6.0                h717dc36_0    conda-forge
superlu                   5.2.1             hfe2efc7_1207    conda-forge
superlu_dist              6.2.0                h5e15a89_2    conda-forge
sympy                     1.6.2            py38h32f6830_0    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1            py38h32f6830_1    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_3    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1007    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

</details>
</summary>

**Comment by ashwinvis** [comment]
Building locally worked for me.

```
❯ conda list | rg mshr                                                                            
mshr                      2019.1.0         py38hf9f41d3_3    file:///home/.../mshr-feedstock/build_artifacts
```

**Comment by laughter9** [comment]
I came over the same issue. Have you solved it? Could you tell me? thx.

**Comment by ashwinvis** [comment]
@laughter9 It was simply a workaround and you need Docker to build locally.
```sh
sudo ./build-locally.py
conda install -c local build_artifacts/linux-64/mshr-2019.1.0-py38hf9f41d3_3.tar.bz2 
```

**Comment by clonker** [comment]
I can report the same problem, perhaps a rebuild of the package can be triggered? @jbweston @minrk

**Comment by tmchartrand** [comment]
I can report the same problem (tested on both python 3.6 and 3.7 versions). Currently working around using the 2018 version.

**Comment by MartinLenzBonn** [comment]
The problem seems to affect only specific builds, it is not necessary to go back to the 2018 version.

On MacOS, the newest build (py38h8c59516_3) produces the ImportError, the second newest (py38h2af9582_2) works for me. Both builds are version 2019.1.0.

The same is true on Ubuntu: The newest build (py38hf9f41d3_3) produces the ImportError, the second newest (py38h255090a_2) works for me. Both builds are version 2019.1.0.

**Comment by clonker** [comment]
I can only emphasize on what @ashwinvis suggested, rebuilding it locally resolved all import issues. In my case i even rebuilt the package on a different machine than the one where the calculations are running (a no-root-access and no docker installed kind of situation).

**Comment by jan-janssen** [comment]
> The problem seems to affect only specific builds, it is not necessary to go back to the 2018 version.
> 
> On MacOS, the newest build (py38h8c59516_3) produces the ImportError, the second newest (py38h2af9582_2) works for me. Both builds are version 2019.1.0.
> 
> The same is true on Ubuntu: The newest build (py38hf9f41d3_3) produces the ImportError, the second newest (py38h255090a_2) works for me. Both builds are version 2019.1.0.

So it seems to be related to the boost version https://github.com/conda-forge/mshr-feedstock/pull/19

**Comment by jan-janssen** [comment]
I am sorry for the delay - I just joined the team of maintainers. The issue should be fixed by the lastest build (it should be available in 1 hour): 
```
conda install -c conda-forge mshr=2019.1.0=*_4
```
This one should fix FEniCS automatically to build 18.
